services:
  comfyui:
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    volumes:
      - "./models:/home/runner/ComfyUI/models:Z"
      - "./user:/home/runner/ComfyUI/user:Z"
      - "./user/input:/home/runner/ComfyUI/input:Z"
      - "./user/output:/home/runner/ComfyUI/output:Z"
    security_opt:
      - "label=type:nvidia_container_t"
    environment:
      - CLI_ARGS=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
