services:
  comfyui:
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    ports:
      - "8188:8188"
    volumes:
      - "./models:/home/runner/ComfyUI/models:Z"
      - "./input:/home/runner/ComfyUI/input:Z"
      - "./output:/home/runner/ComfyUI/output:Z"
      - "./workflows:/home/runner/ComfyUI/pysssss-workflows:Z"
      - "./backgrounds:/home/runner/ComfyUI/backgrounds:Z"
    security_opt:
      - "label=type:nvidia_container_t"
    environment:
      - CLI_ARGS=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
