services:
  comfyui:
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    ports:
      - "8188:8188"
    volumes:
      - "./models:/home/runner/ComfyUI/models"
      - "./input:/home/runner/ComfyUI/input"
      - "./output:/home/runner/ComfyUI/output"
      - "./workflows:/home/runner/ComfyUI/pysssss-workflows"
      - "./backgrounds:/home/runner/ComfyUI/backgrounds"
    environment:
      - CLI_ARGS=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
